# Generated by Django 3.0.4 on 2020-03-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='conn_type',
            new_name='connection_type',
        ),
    ]
